### ISSUE TITLE
Using metadata in Handlebars helper functions

### ISSUE THREAD

**Issue by jmjf** [metalsmith/metadata#10]
I was writing a question about this, but did some more research and figured it out. It wasn't obvious to me, so I'm assuming someone else might be struggle with it too.

If you want to use metadata (global or imported) in a Handlebars helper function, include `options` as your last parameter. Then `options.data.root` will be the global metadata object. If imported a key `foo` with `metalsmith-metadata`, you can access it as `options.data.root.foo`.

Assume `foo.json` is imported to `foo`

```
{
    "bar": "Hello, World!"
}
```

helper, registered as 'foobar'

```
module.exports = function (parm, options) {
    var foo = options.data.root.foo;
    return(foo.bar);
```

Template

```
{{foobar}}
```

will produce output

```
Hello, World!
```

You can also access any file-level metadata in `options.data.root`, for example if you have a title key in your document, `options.data.root.title`

You can get a sense of what's in `options.data.root` by registering the following helper and calling it in a template.

```
module.exports = function (filename, options) {
    var md = options.data.root;
    for (i in md) {
        console.log(i + " | " + md[i]);
    }
};
```

This will log keys and values. Note that some values will be objects, but they should be obvious (`partials`, `knownHelpers`, etc.).

**Metalsmith team**
I'm not sure exactly where this information should go. It's related to using metalsmith-metadata, but also general to metalsmith (global metadata). It's focused on Handlebars helpers, but may apply to other templating engines. Tell me where you want this documented and I'll try to make it happen.

**Comment by JemBijoux** [comment]
Thanks for the writeup on this, was a big help to me.

So a question I have - how did you discover that you could pass in the second `options` argument? Is this a function of handlebars itself, or perhaps of the template engine (consolidate / metalsmith-templates)?

**Comment by jmjf** [comment]
Handlebars helper functions are functions developers write to deal with logic that doesn't fit in Handlebars templates. For example, I wrote a helper to determine if a menu item or any of its descendants (if they exist) is active and return `' active'` or `''` (empty string) so I can inject it into the menu item `<li>`'s `class` attribute (I'm using Bootstrap). So, helper functions can take any parameters the developer wishes to pass.

Handlebars allows passing multiple parameters to helper functions and partials. See the discussion for helpers in the Helpers section at [http://handlebarsjs.com/expressions.html](http://handlebarsjs.com/expressions.html). Partials work the same way.

The `options` object from whence comes `options.data.root` is part of Metalsmith and contains pretty much everything Metalsmith knows about what it's doing. It was either documented somewhere I can't find or was in some code I was looking at when I was trying to get various plugins working. Writing a Handlebars (or other templating engine of your choice) template and partial to recurse and dump `options` (or any other object passed to it) is a revealing exercise everyone should try at least once. All kinds of goodies hidden in `options`. You'll probably end up using the template and partial again later when you're trying to figure out what's in some other hash you're looking at.

Finally, unrelated to this, `consolidate` passes a set of user-defined options to Handlebars, as hinted in the [Notes section](https://github.com/tj/consolidate.js/#notes) (first six bullets reference passing options.partials, options.loader, etc., which get passed through to the engine) and the metalsmith-layouts documentation [https://github.com/superwolff/metalsmith-layouts#consolidate](https://github.com/superwolff/metalsmith-layouts#consolidate).

Hope that helps.

**Comment by oupala** [comment]
@jmjf you can maybe help me on finding a solution in this issue: segmentio/metalsmith-headings#4

I wonder if [metalsmith-navigation](https://github.com/unstoppablecarl/metalsmith-navigation) is similar to [metalsmith-headings](https://github.com/segmentio/metalsmith-headings/)...

**Comment by jmjf** [comment]
Well, metalsmith-navigation generates menu structures nicely, but uses frontmatter metadata in individual markdown files. From what I'm reading, metalsmith-headings looks at the h1, h2, etc., tags in one or more files. So, while it looks like headings would extract all h1, h2, etc., which might be nice for documentation menus, I believe navigation will only extract one item per file. If that's what you want, navigation is the way to go, but if you're trying to build multilevel menus based on heading in the markdown files, you'll need to work with headings.

I do see a problem with the JSFiddle and will note that on the issue.

**Comment by oupala** [comment]
Ok, thanks @jmjf for these explanations.

As far as I understand, metalsmith-navigation is appropriate for generating a navigation menu through a whole site.

metalsmith-headings is appropriate for generating a table of content on one page.

These are different usecases. Choose the appropriate plugin for the appropriate usecase.
