### ISSUE TITLE
yaml not parsed if used with json

### ISSUE THREAD

**Issue by goodpixels** [metalsmith/metadata#14]
my `metalsmith.json`:

```
"metalsmith-metadata": {
    "site": "json/site.json",
    "author": "json/author.json",
    "photos": "yaml/photos.yaml",
    "works": "yaml/works.yaml"
}
```

`site`, `author` parse correctly and are being passed to Handlebars, but `yaml` files are not. i have checked all files (both `.json` and `.yaml`) with JSONLint and YAMLint, and they are all valid.

i even tried parsing _only one_ `yaml` file, but it didn't work. any ideas?

**Comment by wernerglinka** [comment]
Version 1.0.0 supports JSON, YAML and TOML files. Files may be loaded individually or from a directory into an array.
