### ISSUE TITLE
In Windows a .json encoded with UTF8 (With Bom) Return Error of Malformed Data

### ISSUE THREAD

**Issue by mbellet** [metalsmith/metadata#20]
In Windows a .json encoded with UTF8 (With Bom) return error of malformed data.  
BOM is not stripped from the header of the UTF-8 file, if it exists.  
Accurate bug description and solution here: http://stackoverflow.com/questions/24356713/node-js-readfile-error-with-utf8-encoded-file-on-windows

**Comment by wernerglinka** [comment]
Dormant for 6 years.
