### ISSUE TITLE
Preprocess markdown in metadata? 

### ISSUE THREAD

**Issue by JonathanReeve** [metalsmith/metadata#23]
It'd be great if there were an option to preprocess markdown in metadata. At the moment it's a difficult thing to do with metalsmith.

**Comment by wernerglinka** [comment]
Preprocessing markdown can easily be done with a separate plugin. Depending on what templating language you use, this can also be done with filters. For example for Nunjucks you can use something like this:

in the build file add _marked_
```
const marked = require('marked');
```
then build filter
```
const mdToHTML = (mdString) => {
  try {
    return marked.parse(mdString);
  } catch (e) {
    console.error('Error parsing markdown:', e);
    return mdString;
  }
}
```
then define engine options for the in-place and layouts plugins. these options are passed to the Nunjucks templating engine
```
const templateConfig = {
  engineOptions: {
    path: [`${workingDir}/layouts`],
    filters: {
      mdToHTML,
    },
  },
};
```
then apply the options to in-place
```
.use(inplace(templateConfig))
```
Now you can use this filter in the template like this
```
{{ info.prose | mdToHTML | safe }}
```
