### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by willeastcott** [metalsmith/metadata#28]
I've been migrating the [PlayCanvas Developer Site](https://github.com/playcanvas/developer.playcanvas.com) to the shiny new @metalsmith-prefixed NPM packages. Great to see these being updated! Is the metadata plugin going to be published to NPM as @metalsmith/metadata soon?

**Comment by wernerglinka** [comment]
Hi @willeastcott, thanks for checking in. The metadata plugin is still WIP, I'll be out on vacation until second week in March but then it should be soon. 
And congrats for migrating the PlayCanvas Developer Site. It is good to see that the community is starting to grow again.
