### ISSUE TITLE
Incompability with metalsmith-watch

### ISSUE THREAD

**Issue by aymericbeaumet** [metalsmith/metadata#3]
Hello,

I'm encountering an issue when using this plugin along with the `metalsmith-watch` plugin.

The problem is that the `metalsmith-watch` plugin calls the middleware stack and only passes the files that actually changed (which is the expected behavior). Therefore when `metalsmith-metadata` try to loads the desired metadata files, they do not exists anymore (unless they have been edited). And so it throws an error.

**Comment by fizzydigital** [comment]
@aymericbeaumet have you managed to resolve this issue? could you possibly share your solution?

**Comment by aymericbeaumet** [comment]
@fizzydigital unfortunately no solutions so far, I think I ended up using something like nodemon
