### ISSUE TITLE
Possible to get example of use

### ISSUE THREAD

**Issue by seffw** [metalsmith/metadata#6]
I have the following, as shown in the readme:

.use(metadata({
    templatedata: 'templatedata.yaml'
}))

and 

templatedata.yaml in the 'src' directory (containing varname: value)

But varname when used in a template is not recognised

I think I just need to do more, but I can not see an example of use (and that is something that can help others too).

EDIT: tried also with .json and json data form, same result. No global metadata (at least not available to templates)

**Comment by RobLoach** [comment]
In your template, it should be presented as `templatedata.varname`.
